local ReplicatedStorage = game:GetService("ReplicatedStorage")
require(ReplicatedStorage.Shared.modules.core.registries.Quests)
require(ReplicatedStorage.Shared.modules.core.registries.Zones)
require(ReplicatedStorage.Shared.modules.core.registries.LootTables)
require(ReplicatedStorage.Shared.modules.core.registries.Upgrades)
require(ReplicatedStorage.Shared.modules.core.registries.Items)
require(ReplicatedStorage.Shared.modules.core.registries.Ores)

require(ReplicatedStorage.Shared.modules.core.registries.NPCs)

-- dialogue
require(ReplicatedStorage.Shared.modules.core.registries.dialogue.DialogueEntries)
require(ReplicatedStorage.Shared.modules.core.registries.dialogue.DialogueNodes)
require(ReplicatedStorage.Shared.modules.core.registries.dialogue.DialogueConditions)
require(ReplicatedStorage.Shared.modules.core.registries.dialogue.DialogueCommands)

return {}
